[run]
timeout = "120s"

[output]
format = "colored-line-number"

[linters]
enable = [
    "gocyclo", "unconvert", "goimports", "unused",
    "vetshadow", "misspell", "nakedret", "errcheck", "ineffassign",
    "goconst", "vet", "unparam", "gofmt"
]

[issues]
exclude-use-default = false